### PR TITLE
Autohide unneeded options and other tweaks

### PR DESCRIPTION
**Pull request by rmcanany**
To test autohide, check `Option 1` from `Task number 1-10`.  

Note, I added your magic `OnCreateControl`, code to the main form.  I also removed the border from the `TLP` and added a border to the `UserControl`.  I'm not too fond of the border color, but it looks like I can inherit that control and tweak as needed.

### CODE REVIEW

**Comment by rmcanany** [comment]
Not sure why it's complaining about conflicts.  I pulled from the repo this morning.  Do I need to update my GitHub repo to get your most recent code or something?

If it's going to trash your project, feel free to reject this PR.

**Comment by rmcanany** [comment]
Yeah, my fork is 6 commits behind yours.  I'll get it sorted out tomorrow.

**Comment by farfilli** [comment]
Yes, it's always best to synch before changing the code to avoid conflicts.

Anyway it's a test project, don't worry about trashing it 😂

**Comment by rmcanany** [comment]
That was very helpful.  Thank you for putting it together for me.  

I broke it beyond recognition, so am not going to make a PR.  I learned what I needed, though.

**Pull request closed without merging**
